FROM node:14.19.3-alpine

WORKDIR /usr/src/app

RUN apk update \
  && apk add bash git curl \
  && rm -rf /var/cache/apk/*

COPY . .

RUN yarn global add nx \
  && yarn install \
  && rm -rf $(yarn cache dir)
