FROM node:16.20-alpine

WORKDIR /usr/src/app

RUN apk update \
  && apk add bash git curl \
  && rm -rf /var/cache/apk/*

COPY . .

RUN yarn install \
  && rm -rf $(yarn cache dir)

CMD ["./apps/main-e2e/bin/serve.sh"]
