version: '3.7'

services:
  main-db:
    image: postgres:17.4
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - main-db-data:/var/lib/postgresql/data

volumes:
  main-db-data:
