/* This file was automatically generated with route-codegen and should not be edited. */
export * from "./xhrLogin/patternXhrLogin";
export { default as generateUrlXhrLogin } from "./xhrLogin/generateUrlXhrLogin";
export * from "./xhrSignup/patternXhrSignup";
export { default as generateUrlXhrSignup } from "./xhrSignup/generateUrlXhrSignup";
export * from "./graphql/patternGraphql";
export { default as generateUrlGraphql } from "./graphql/generateUrlGraphql";
export * from "./logout/patternLogout";
export { default as generateUrlLogout } from "./logout/generateUrlLogout";
export * from "./me/patternMe";
export { default as generateUrlMe } from "./me/generateUrlMe";
export * from "./home/patternHome";
export { default as generateUrlHome } from "./home/generateUrlHome";
export * from "./login/patternLogin";
export { default as generateUrlLogin } from "./login/generateUrlLogin";
export * from "./signup/patternSignup";
export { default as generateUrlSignup } from "./signup/generateUrlSignup";
export * from "./termAndConditions/patternTermAndConditions";
export { default as generateUrlTermAndConditions } from "./termAndConditions/generateUrlTermAndConditions";
export * from "./privacyPolicy/patternPrivacyPolicy";
export { default as generateUrlPrivacyPolicy } from "./privacyPolicy/generateUrlPrivacyPolicy";
export * from "./clientSeoStaticImage/patternClientSeoStaticImage";
export { default as generateUrlClientSeoStaticImage } from "./clientSeoStaticImage/generateUrlClientSeoStaticImage";
export * from "./static404/patternStatic404";
export { default as generateUrlStatic404 } from "./static404/generateUrlStatic404";
export * from "./static500/patternStatic500";
export { default as generateUrlStatic500 } from "./static500/generateUrlStatic500";
