name: CI
on:
  push:
    branches-ignore:
      - 'master'

env:
  node-version: '22.x'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  precheck:
    name: Check jobs to run
    runs-on: ubuntu-22.04
    outputs:
      affected-main: ${{ steps.affected.outputs.main }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: Check affected apps
        id: affected
        run: |
          main_affected=`./ops/bin/check-affected.sh app main origin/master`
          echo "::set-output name=main::$main_affected"

  main:
    name: Main app CI
    runs-on: ubuntu-22.04
    needs: precheck
    if: ${{ needs.precheck.outputs.affected-main == 'true' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install deps
        run: yarn install --prefer-offline

      - name: Codegen main-prisma
        run: yarn nx codegen main-prisma
        env:
          PRISMA_BINARY_TARGET: '["linux-musl"]'

      - name: Lint
        run: yarn nx lint main

      - name: Build
        run: yarn nx build main

      - name: Test - Unit
        run: yarn nx test main

      - name: Test - e2e - Setup
        run: yarn nx run main-e2e:setup:prod

      - name: Test - e2e - Run
        id: test-main-e2e-run
        run: yarn nx run main-e2e:run:docker

      - name: Upload failed e2e artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: main-e2e-cypress-artifacts
          path: dist/cypress

      - name: Test - e2e - Teardown
        if: always()
        run: yarn nx run main-e2e:teardown
