name: CI
on:
  push:
    branches-ignore:
      # Ignore the commits that are created when PR is merged into master
      - "master"
jobs:
  build:
    name: Build and check assets
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Copy common files
        run: yarn common:copy

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Check route-codegen DEV
        run: ./ci/scripts/check-generated-routegen-dev.sh

      - name: Check GraphQL codegen
        run: ./ci/scripts/check-generated-graphql-codegen.sh

      - name: Generate prisma
        run: yarn prisma:generate:prod

      - name: Build all assets
        run: yarn build
