name: CI
on:
  push:
    branches-ignore:
      # Ignore the commits that are created when PR is merged into master
      - "master"
jobs:
  check-code:
    name: Check generated code and linting
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Copy common files
        run: yarn copy:common

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Check route-codegen DEV
        run: ./scripts/ci/check-generated-routegen-dev.sh

      - name: Check GraphQL codegen
        run: ./scripts/ci/check-generated-graphql-codegen.sh

      - name: Generate prisma
        run: yarn prisma:generate:native

      - name: Lint
        run: yarn lint

  build-client:
    name: Build client
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Copy common files
        run: yarn copy:common

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:client

  build-client-seo:
    name: Build client-seo
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Copy common files
        run: yarn copy:common

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:client-seo

  build-server-apps:
    name: Build server apps
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Copy common files
        run: yarn copy:common

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Generate prisma
        run: yarn prisma:generate:native

      - name: Build server main app
        run: yarn build:server:app

      - name: Build server crons
        run: yarn build:server:crons

      - name: Build server libs
        run: yarn build:server:libs

  test-frontends:
    name: Test frontends
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Copy common files
        run: yarn copy:common

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Test common
        run: yarn test:common:unit

      - name: Test client
        run: yarn test:client:unit

      - name: Test client-seo
        run: yarn test:client-seo:unit

  test-server-app:
    name: Test server app
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Copy common files
        run: yarn copy:common

      - name: Test server app
        run: yarn test:server:app

      - name: Run Insider
        uses: insidersec/insider-action@v0
        with:
          technology: javascript
          target: services/server/src
