Remove this line to activate this workflow
name: Deploy client
on:
  push:
    branches:
      - "master"
    paths:
      - "common/**"
      - "route-manager/**"
      - "client/**"
jobs:
  deploy:
    name: Build and deploy client
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Copy common files
        run: yarn common:copy 

      - name: Route codegen PROD
        run: yarn routegen:prod

      - name: Build assets
        run: yarn build:client

      - name: Deploy
        uses: aaronpanch/action-serverless@master
        with:
          args: deploy --debug
        env:
          SERVICE_ROOT: ./client
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CI }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CI }}